version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - app-network

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env.docker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    depends_on:
      - redis
      - postgres
    env_file:
      - .env.docker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
